# Generated by Django 4.2 on 2023-06-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShare', '0002_users_admin_users_confirmado_users_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
