# Generated by Django 4.2 on 2023-06-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShare', '0004_users_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citasservicios',
            old_name='Servicios',
            new_name='serviciosId',
        ),
    ]
