# Generated by Django 4.2 on 2023-06-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShare', '0006_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
