# Generated by Django 4.2 on 2023-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShare', '0007_remove_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
